### ISSUE TITLE
Add concept of project or workspace to WES

### ISSUE THREAD

**Issue by ghost** [ga4gh/workflow-execution-service-schemas#158]
The current published WES specification has no provision for organizing executions. Executions go into a flat space. A user may wish to organize the executions however. SB powered platforms have concepts of Projects, Terra has a concept of workspaces, for example. On HPC executions users may choose to persist execution products or logs or other meta information in a particular folder, or space.

The SB WES implementation currently uses a custom parameter `project` in the `workflow_params` field. It would be useful to standardize how to do this by having an optional parameter that can be used to instruct the engine where executions can be organized.

For example, we could have a parameter `execution_location` with type string which refers to a path that the host platform/executor will use to organize the executions.

This parameter should be present in all calls that 
1. Start executions
2. List executions

Thanks!

**Comment by ruchim** [comment]
hey @kaushik-work  -- it sounds like we're introducing a concept of "working directory" into the WES implementation -- which is a utility that lets a client dictate "where" the outputs of a run go. Does this imply anything other than a directory on a local filestore or a pseudo-directory type thing in a cloud storage system?

There might an access notion we have to solve for here as well -- for example is the WES implementation using the same token to do this move, or if that token doesn't have the scopes, how do additional tokens get added?

**Comment by patmagee** [comment]
This feels like it should be an implementation specific detail provided in the `workflow_engine_parameters`. Enforcing the concept of a workspace on all WES implementations might not be possible and also makes adoption of the standard more difficult. `execution_location` is quite a nebulous idea which will mean entirely different things in every setting.

One current roadblock to this is that there is no real way for an engine to define ALL of the `workflow_engine_parameters` that it allows. I wonder if instead ofa just having the `default_engine_parameters` showing the default value there was an object like:

```json
"available_engine_parameters": {
   "execution_location": {
      "description": "the location that you would like to run this execution in. Must be one of [ ... , ... ]
      "type": "String",
      "default_value": "/some/path"
   }
}
```

While this wont be the one magic bullet that forces all wes implementations to implement the `execution_location` it would at least allow the `service-infor` endpoint to be more descriptive in what engine parmaters it offers. This could be use to build more intuitive UIs and clients for end users

**Comment by vinjana** [comment]
We have this use case for a [WES implementation](https://gitlab.com/one-touch-pipeline/weskit) that should serve as our backend for a data management and automation system. We want to leave the functionality of setting permissions on the output directories to the data management system, because we think this is not the purpose of WES. This means, we first let the data management system create the directory with restrictive permissions, then run the workflow via the WES in this directory, and if the results are ready and validated, we open the permissions to the relevant users. 

The work/execution directory is simply the directory in which the workflow engine is executed, because thus we can exploit that the workflow engines write their logs etc. in there, which is s.th. we want to provide to the data users. This avoids that we have to bend a lot of environment and configuration variables for the engine and simplifies the overall implementation. This works very well for at least Nextflow and Snakemake, and I expect it to work also for most other engines, because it is so close to the way these engines are usually called by end-users on the CLI.

@patmagee I don't think that it is necessary to define all workflow engine parameters or that this is a blocker. It would just be necessary to define this engine parameter as a reserved key among the engine parameters -- "execution_location" or whatever. Reserving keys may cause clashes with (future) engines. So, alternatively, maybe it is worthwhile considering the ideas in #171, and implement the execution directory as a dedicated parameter category/slot. I think this also makes semantically sense: I'm not aware of an engine that has an "execution directory" option. Also workflows don't usually have an "execution directory" parameter. Rather engines and their workflows access the execution directory as an environmental factor (with `os.getwd()`, or whatever).

**Comment by patmagee** [comment]
@vinjana those are valid points and you definitely have a specific use case that would benefit from this sort of behaviour. I sitll think this exposes to much implementation details to the end user which may or may not be usable. The challenge with defining a single standard like `WES` is that you are trying to satisfy the operational semantics of many different workflow languages and engines with a singular standard, and we are each heavily biased by the current system we use. I would say the goal of a standard like `WES` should be to provide an abstraction for distributed analysis through an API. While the underlying engine could be implemented using a `cli` runtime, I do not think the normal concepts of running on a single workstation (or cluster) with a file system attached should apply (especially as we push towards `DRS` based file references).

For example:

> because it is so close to the way these engines are usually called by end-users on the CLI.

Seems to implicate that alot of analysis are launched directly from the commandline. While this is true for nextflow and snakemake, a huge portion of the WDL and CWL community will never launch a workflow from the command line. So things like `execution directory` make sense only insofar as the cloud bucket that data is eventually moved to, and even then that is not always the case in proprietary abstracted environments (ie DNAnexus or SB).

Ultimately I am really not against the idea per-say, I would just be hesitant to include this as a specific configuration option when it seems to really be focused on a subset of specific use cases vs servicing the WES community as a whole. I would be 100% behind a more robust system that allows implementations to define their own engine parameters in a machine readable way as I suggested above. This would definitely cover you're use case and allow other clients of `WES` to discover available engine parameters.

**Comment by vinjana** [comment]
You're right. A use case in which a workflow is executed by streaming data directly from and to S3 was not a use case that I had in mind. I also understand, that you don't want to have a standard that explicitly models many different use cases (e.g. by reserving keys), but rather want to have a very flexible and abstract standard, that can be reused in all of the current and future use cases. 

The idea to communicate implementation-specific parameters as machine readable service information is certainly a more flexible approach, than reserving names for engine parameters.

Thanks for the clarification!
